travis:
  secure:
    BINSTAR_TOKEN: ffJHC0xArUkjYNC9H467Nzjvl4jCq7TbU//cInSSnRRi/iHG+LMTxZ0mq1MLd+kdRXRPKZHiSb27wuBwg67s9uaimlFQFS+vYSoCI6a835oRwJb08LRAmPibofUJlgEdAE/eUKrFExFJ/K0l55Llk1ssD12+3bcjn5GS0yfLo4K5s7SpUMSeVC4U/Z2Lxt2UoTlmgjv8X6udegyqSP3dSlN7DvoD73qAcoe+fuuNEPWogGBuhzqqXvmhM8Owb1NrloKD68AElu2m9DBExwSdT1iphic4KkbQ9nbbqeB6yGQSzNoYpdtUDkZvB3dETnBRad1k28jzhmipu+f/CuVGVIA1E1O1WDii2JWauwCNi8lPR3sz7uPB4129TFPCobsV8MDscvSIhTBH2jqOSQJyvbiwcWw3e5GWPhtLKjrvQ0+Vm8mpSmmJhsK8F4qsTIoAUmTv05cDuWdBVuwMPFQIJgGYShFyvajimdey4O20Wy1pm4TjXWpgqU4lIDarOLqqjRRR+uEdl9TAU6QYptJFDCIio0Cf59YDbqvgm/SeCs1a33c/GDlKqt4ORF2pgdDV/S/+lwK1SwYGlaXY+CIa2VcvHQZFmI+mwwc0wAqn6mVvI740WGlZXrIeAbZMNQby+10ozjtqljgC4Mk8PZMQ5Bu4ZSmqR5+rivenoJxRBX0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
