travis:
  secure:
    BINSTAR_TOKEN: tNNhQJz9VuUMI0/j1z71esCNC2adOHh+gJKuGoa3VLy5onSi511IhuIWWrXhOLnztoqodMMXdFmgD/nQsC2/QwVt94lSAPA2fBFSaNItMID4k2im1w6du1oE41g94SSy3Z9w+zuHXXZEBewmpySo52BRMRPbW3TNIkOQOtMyotZ5ynK2D10kVtAZpyxJV1wJPjcEJeKSs7erSH+ewBKM4TEdwwvxnyyOfembFK5ElYNVJVR+Emeuc+fzaUqeqpVSpgptCFdOThIRELJI2200nbCOpEGeKfV08Q8VQNNrjIc5dpfUnTV6DEAUEVINZJxHn27U6wfcAtrlsVSSaNGsr4BXCIAA5+vX0BtZYHsGAPgKciQz3nlp7rz+FoorZ0XRtWNMRgDpQjADzYLSjjC3QQifehUhR8La/QhVZQ+V96YBYvr/aapkcKIVfUch4KHjV4Xb2cgwAvnQmKaRg43+2JULXuKB3IsL3I/Oa2hbfaHc57HiISlYRX4bOX/OfKqDRa0tQXrH2QJTJDIlgAgEor15HNGOJNDuhviCZU4ZGcdJzv1gZhY9RdWN2SlvT3J+StzVz3Q9ZRBvY8eeRI5G+F6KE646KJeUsTtC7rhiUdilob+qp1OIBL2y/Thcs3Qw5fMHbRg4zKG7Bdhtf08xBQYvzWWlpm8RixupuvuxxQ8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
